# Generated by Django 2.2.2 on 2019-06-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0003_auto_20190624_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
