# Generated by Django 2.2.2 on 2019-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(),
        ),
    ]
