# Generated by Django 2.2.2 on 2019-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0006_auto_20190627_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='type',
            field=models.CharField(choices=[('update', 'Update'), ('discussion', 'Discussion'), ('meme', 'Meme')], default='discussion', max_length=20),
        ),
    ]
