# Generated by Django 2.2.2 on 2019-07-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0007_thread_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='type',
            new_name='flair',
        ),
    ]
