# Generated by Django 2.2.2 on 2019-07-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0008_auto_20190702_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(to='MetaGrab.Game'),
        ),
    ]
