# Generated by Django 2.2.2 on 2019-07-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0011_auto_20190704_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
