# Generated by Django 2.2.2 on 2019-07-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0014_auto_20190710_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='games',
            new_name='followed_games',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thread',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MetaGrab.Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_thread',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='MetaGrab.Thread'),
            preserve_default=False,
        ),
    ]
