# Generated by Django 2.2.2 on 2019-07-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0015_auto_20190710_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MetaGrab.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MetaGrab.Thread'),
        ),
    ]
