# Generated by Django 2.2.2 on 2019-07-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0016_auto_20190712_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.URLField(default='https://images2.alphacoders.com/474/thumb-1920-474206.jpg'),
        ),
    ]
