# Generated by Django 2.0.13 on 2019-08-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0018_auto_20190822_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
