# Generated by Django 2.0.13 on 2019-11-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0021_auto_20191104_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='commentsecondary',
            name='content',
            field=models.TextField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
