# Generated by Django 2.0.13 on 2019-11-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0022_auto_20191104_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsecondary',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentsecondary',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MetaGrab.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MetaGrab.Thread'),
        ),
        migrations.DeleteModel(
            name='CommentSecondary',
        ),
    ]
