# Generated by Django 2.0.13 on 2019-11-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0023_auto_20191107_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='num_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='num_childs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='num_subtree_nodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='num_childs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='num_subtree_nodes',
            field=models.IntegerField(default=0),
        ),
    ]
