# Generated by Django 2.0.13 on 2019-11-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0024_auto_20191108_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='flair',
            field=models.IntegerField(choices=[(0, 'Update'), (1, 'Discussion'), (2, 'Meme')], default=1),
        ),
    ]
