# Generated by Django 2.0.13 on 2019-11-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0025_auto_20191115_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='flair',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1),
        ),
    ]
