# Generated by Django 2.0.13 on 2019-11-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0028_auto_20191121_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image_url',
            field=models.URLField(default=None),
        ),
    ]
