# Generated by Django 2.0.13 on 2019-12-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0029_thread_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner',
            field=models.URLField(default='https://res.cloudinary.com/dzengcdn/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative,l_text:montserrat_25_style_light_align_center:Shop%20Now,w_0.5,y_0.18/v1575913613/dota2_tkcbuh.jpg', max_length=500),
        ),
    ]
