# Generated by Django 2.0.13 on 2019-12-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0030_game_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_positive',
        ),
        migrations.AddField(
            model_name='vote',
            name='direction',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1)], default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.URLField(default='https://res.cloudinary.com/dzengcdn/image/upload/c_fill,g_auto,h_250,w_970/b_rgb:000000,e_gradient_fade,y_-0.50/c_scale,co_rgb:ffffff,fl_relative/v1575913613/dota2_tkcbuh.jpg', max_length=500),
        ),
    ]
