# Generated by Django 2.0.13 on 2019-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0031_auto_20191213_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_expansion_release_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
