# Generated by Django 3.0.4 on 2020-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0034_auto_20200219_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_summary',
            field=models.TextField(default='This game is awesome', max_length=40000),
            preserve_default=False,
        ),
    ]
