# Generated by Django 3.0.6 on 2020-05-11 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MetaGrab', '0035_game_game_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blacklisted_user_profiles',
            field=models.ManyToManyField(related_name='_userprofile_blacklisted_user_profiles_+', to='MetaGrab.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hidden_comments',
            field=models.ManyToManyField(to='MetaGrab.Comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hidden_threads',
            field=models.ManyToManyField(to='MetaGrab.Thread'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reported_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MetaGrab.Comment')),
                ('reported_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MetaGrab.Thread')),
                ('reportee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
