# Generated by Django 3.0.6 on 2020-07-16 19:05

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0039_genre_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image_dimensions',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
