# Generated by Django 3.0.6 on 2020-07-16 19:32

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0040_thread_image_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='image_dimensions',
        ),
        migrations.AddField(
            model_name='thread',
            name='image_heights',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='thread',
            name='image_widths',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
