# Generated by Django 3.0.6 on 2020-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGrab', '0042_auto_20200721_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_width',
            field=models.IntegerField(default=0),
        ),
    ]
